// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uybezyecqdtgmizlruxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5YmV6eWVjcWR0Z21pemxydXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjA0NzIsImV4cCI6MjA2OTg5NjQ3Mn0.G2ycKOyInKBApqQx9vLTzmCLxJqKm90bdJrwGgeGdsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});